function PlotComplianceHistory(Y1)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data (Compliance)

%  Auto-generated by MATLAB on 16-Aug-2018 18:11:26

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',24,'FontName','Times New Roman');
%% Uncomment the following line to preserve the Y-limits of the axes
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'on');

% Create plot
plot([1:length(Y1)],Y1,'LineWidth',3);

% Create xlabel
xlabel('Iterations');

% Create ylabel
ylabel('Compliance (Nm)');

end

